import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SRSLoadAlertDialog from "./_components/srs-load-alert-dialog";
import { ThemeProvider } from "next-themes";
import { themes } from "@/lib/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body className={cn(inter.className, "h-full")}>
        <ThemeProvider
          themes={themes.map((theme) => theme.name)}
          attribute="class"
          defaultTheme={themes[0].name}
          disableTransitionOnChange
        >
          {children}
          <SRSLoadAlertDialog />
        </ThemeProvider>
      </body>
    </html>
  );
}
