import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SRSLoadAlertDialog from "./_components/srs-load-alert-dialog";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="polar h-full">
      <body className={cn(inter.className, "h-full")}>
        {children}

        <SRSLoadAlertDialog />
      </body>
    </html>
  );
}
